version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - store_artifacts:
          path: ~/output

workflows:
  version: 2
  aws-cli:
    jobs:
      - build:
          context: AWS
